[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
actix-web = "4.0"
mime = "0.3"
actix-multipart = "0.6.1"
actix-cors = "0.6.5"
lettre = "0.11.2"
sqlx = { version = "0.5", features = ["runtime-actix-native-tls", "postgres"] } 
serde = "1.0.193"